steps:
  - name: python
    entrypoint: python
    args: ["pip", "install", "--upgrade", "pip"]

  - name: python
    entrypoint: python
    args: ["pip", "install", "-r", "requirements.txt"]

  - name: python
    entrypoint: python
    args: ["pip", "list"]

  - name: python
    entrypoint: python
    args: ["train_deploy.py"]

options:
  logging: CLOUD_LOGGING_ONLY
