steps:
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "-r", "requirements.txt"]

  - name: python
    entrypoint: python
    args: ["train_deploy.py"]

options:
  logging: CLOUD_LOGGING_ONLY
