steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/tensile-nebula-406509/my-image:latest", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["run", "gcr.io/tensile-nebula-406509/my-image:latest"]

timeout: 9000s

options:
  logging: CLOUD_LOGGING_ONLY
