steps:
   - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', 'requirements.txt']
  
  - name: python
    entrypoint: python
    args: ["train_deploy.py"]

options:
  logging: CLOUD_LOGGING_ONLY
