steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: attach-date
    args:
      - bash
      - -c
      - |
        pip install requirements.txt
  
  - name: python
    entrypoint: python
    args: ["train_deploy.py"]

options:
  logging: CLOUD_LOGGING_ONLY
